name: build-all.yml

on:
  workflow_dispatch:

jobs:

  matrix:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.r }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    strategy:
      matrix:
        config:
        - { r: 'devel' }
        - { r: 'next'  }
        - { r: '4.5.1' }
        - { r: '4.3.3' }
        - { r: '4.2.3' }
        - { r: '4.1.3' }
        - { r: '4.0.5' }
    steps:
    - id: set-matrix
      run: echo "matrix=${{ toJson(matrix) }}" >> $GITHUB_OUTPUT

  amd64:
    needs: matrix
    uses: ./.github/workflows/build-one.yml
    strategy:
      matrix:
        config: ${{ fromJson(needs.matrix.outputs.matrix) }}
    with:
      platform: 'amd64'
      runs-on: 'ubuntu-latest'
      rversion: ${{ matrix.config.r }}
    secrets: inherit

  arm64:
    needs: matrix
    uses: ./.github/workflows/build-one.yml
    strategy:
      matrix:
        config: ${{ fromJson(needs.matrix.outputs.matrix) }}
    with:
      platform: 'arm64'
      runs-on: 'ubuntu-24.04-arm'
      rversion: ${{ matrix.config.r }}
    secrets: inherit

  manifest:
    needs: [matrix, amd64, arm64]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - run: |
        for tag in ${{ needs.amd64.outputs.tags }}; do
          echo docker buildx imagetools create -t $tag \
            ghcr.io/r-hub/r-minimal/r-minimal:${{ matrix.config.r }}-amd64 \
            ghcr.io/r-hub/r-minimal/r-minimal:${{ matrix.config.r }}-arm64;
        done
      shell: bash
